server:
  port: ${SERVER_PORT:8080}

spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://${PGHOST:localhost}:5432/${PGDATABASE:neondb}}
    username: ${SPRING_DATASOURCE_USERNAME:${PGUSER:postgres}}
    password: ${SPRING_DATASOURCE_PASSWORD:${PGPASSWORD:}}
    driver-class-name: org.postgresql.Driver
  sql:
    init:
      mode: always
      continue-on-error: true
  jpa:
    defer-datasource-initialization: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

app:
  jwt:
    secret: ${APP_JWT_SECRET}
    expiration-ms: 86400000 # 24 hours
  upload:
    dir: uploads
  openweathermap:
    api-key: ${OPENWEATHERMAP_API_KEY:}

spring.mvc.async.request-timeout: 300000
